services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db # Backend zależy od bazy danych
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always

  db: 
    image: postgres:17-alpine # Lżejszy obraz PostgreSQL
    container_name: data_visualize_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:

      - dataVisualize_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  dataVisualize_db_data: # Definicja nazwanego wolumenu
